name: Build Kivy APK

on: 
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Опционально: принудительно использовать Node.js 24
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    
    steps:
      - uses: actions/checkout@v4
        # actions/checkout@v4 все еще использует Node 20, но работает
      
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v2
        id: buildozer
        with:
          workdir: .
          buildozer_version: stable
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-android-app
          path: ${{ steps.buildozer.outputs.filename }}
          if-no-files-found: error
